
package project.hrms.core.adapters.MernisServiceReference;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: D5BE7513681F1DD3A49F6F2224FF761614E01F75DF84A5237FFCB580C2100F2FD6B3D2E5CAA8F81376163A7C93B588EDFA6AFC9A122C3FE14A58F30C070592BD
//------------------------------------------------------------------------
public interface NCEDateTimeParser
{
    String getStringFromDateTime(java.time.ZonedDateTime date);
    String getStringFromDate(java.time.LocalDate date);
    String getStringFromTime(java.time.LocalTime date);
    String getStringFromDuration(java.time.Duration date);
    java.time.ZonedDateTime parse(String value);
    java.time.LocalDate parseLocal(String value);
    java.time.Duration parseDuration(String value);
    java.time.LocalTime parseTime(String value);
}
