

package project.hrms.core.adapters.MernisServiceReference;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: D5BE7513681F1DD3A49F6F2224FF761614E01F75DF84A5237FFCB580C2100F2FD6B3D2E5CAA8F81376163A7C93B588EDFA6AFC9A122C3FE14A58F30C070592BD
//------------------------------------------------------------------------

public class NCESoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public NCESoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public NCESoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}